Add spec for Configurator
Hexanet/SwarrotStatsdBundle pull request #3
Opened 2017-10-10 19:33 UTC by notFloran

2017-10-10 19:45 UTC, nclsHart requested changes

2017-10-10 19:45 UTC, nclsHart commented on spec/Configurator/StatsdProcessorConfiguratorSpec.php
> +    function it_returns_processors_arguments($eventDispatcher)
processor

2017-10-10 19:45 UTC, nclsHart commented on spec/Configurator/StatsdProcessorConfiguratorSpec.php
> +    function it_resolve_options(InputInterface $input)
resolves

2017-10-11 05:25 UTC, notFloran commented on spec/Configurator/StatsdProcessorConfiguratorSpec.php
> +    function it_returns_processors_arguments($eventDispatcher)
done

2017-10-11 06:43 UTC, nclsHart approved these changes

2017-10-11 06:43 UTC, merged